#
# Makefile for industrial I/O Light sensors
#

obj-$(CONFIG_SENSORS_TSL2563)	+= tsl2563.o
obj-$(CONFIG_SENSORS_ISL29018)	+= isl29018.o
obj-$(CONFIG_SENSORS_ISL29023)	+= isl29023.o
obj-$(CONFIG_SENSORS_ISL29028)	+= isl29028.o

